### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by akneves** [reachsumit/deep-unet-for-satellite-image-segmentation#3]
Hello,
I tested your training and predict codes on my pc to study image segmentation with deep learning. But I have some questions (both about "predict.py") that I would appreciate if you could answer me. 
1- why it was necessary to "fill extended image with mirrors"? - line 19
2- why did you have to make some image reverses (after "for i in range(7)...") to get the image segmentation? - line 76

thanks for your attention.

**Comment by patrickcgray** [comment]
Hey @akneves did you ever find the answer to your second question? I'm not quite clear on that chunk of code either.

@reachsumit any explanation as to why that was done? Are you doing this to get some sort of rotation invariance? Shouldn't that be taken care of by image augmentation rather than in the prediction step?

**Comment by reachsumit** [comment]
The idea is to apply multiple augmentations to the single test image. Then ask the network to make predictions on each of the augmented images. Then "undo" the augmentation and take an average of predictions made for each pixel.
